import type {
  CatalogChallenge,
  CatalogCreator,
  CatalogPerk,
} from "@creator-platform/shared";

export const DEMO_CREATORS: readonly CatalogCreator[] = [
  {
    id: "lena-music",
    handle: "lenamusic",
    displayName: "Lena Music",
    bio: "Singer and songwriter creating new releases with her community.",
    category: "Music",
    tokenName: "Lena",
    tokenSymbol: "LENA",
    followersCount: 24_800,
    activeChallengesCount: 2,
    perksCount: 3,
    verified: true,
    featured: true,
    trending: true,
    recentlyActive: true,
    createdAt: "2025-02-11T00:00:00.000Z",
    source: "demo",
  },
  {
    id: "nova-wave",
    handle: "novawave",
    displayName: "Nova Wave",
    bio: "Video creator, editor, and visual storyteller.",
    category: "Video",
    tokenName: "Nova",
    tokenSymbol: "NOVA",
    followersCount: 18_200,
    activeChallengesCount: 2,
    perksCount: 2,
    verified: true,
    featured: true,
    trending: false,
    recentlyActive: true,
    createdAt: "2025-03-04T00:00:00.000Z",
    source: "demo",
  },
  {
    id: "mika-live",
    handle: "mikalive",
    displayName: "Mika Live",
    bio: "Live creator building shows together with the audience.",
    category: "Streaming",
    tokenName: "Mika",
    tokenSymbol: "MIKA",
    followersCount: 31_400,
    activeChallengesCount: 1,
    perksCount: 2,
    verified: true,
    featured: true,
    trending: true,
    recentlyActive: true,
    createdAt: "2024-11-20T00:00:00.000Z",
    source: "demo",
  },
  {
    id: "beatlab",
    handle: "beatlab",
    displayName: "BeatLab",
    bio: "Producer community for beats, remixes, and live sessions.",
    category: "Music",
    tokenName: "Beat",
    tokenSymbol: "BEAT",
    followersCount: 12_700,
    activeChallengesCount: 2,
    perksCount: 2,
    verified: true,
    featured: false,
    trending: true,
    recentlyActive: true,
    createdAt: "2025-01-08T00:00:00.000Z",
    source: "demo",
  },
  {
    id: "ava-studio",
    handle: "avastudio",
    displayName: "Ava Studio",
    bio: "Digital artist exploring illustration, animation, and fan-made worlds.",
    category: "Art",
    tokenName: "Ava",
    tokenSymbol: "AVA",
    followersCount: 16_900,
    activeChallengesCount: 2,
    perksCount: 2,
    verified: true,
    featured: false,
    trending: false,
    recentlyActive: true,
    createdAt: "2025-04-17T00:00:00.000Z",
    source: "demo",
  },
  {
    id: "rue-archive",
    handle: "ruearchive",
    displayName: "Rue Archive",
    bio: "Fashion concepts, styling challenges, and limited community drops.",
    category: "Fashion",
    tokenName: "Rue",
    tokenSymbol: "RUE",
    followersCount: 9_600,
    activeChallengesCount: 0,
    perksCount: 1,
    verified: false,
    featured: false,
    trending: false,
    recentlyActive: false,
    createdAt: "2025-05-02T00:00:00.000Z",
    source: "demo",
  },
  {
    id: "pixel-forge",
    handle: "pixelforge",
    displayName: "Pixel Forge",
    bio: "Speedrunning and game-dev community shipping small games together.",
    category: "Gaming",
    tokenName: "Pixel",
    tokenSymbol: "PXL",
    followersCount: 21_300,
    activeChallengesCount: 0,
    perksCount: 1,
    verified: true,
    featured: false,
    trending: false,
    recentlyActive: true,
    createdAt: "2025-06-01T00:00:00.000Z",
    source: "demo",
  },
  {
    id: "slow-living-co",
    handle: "slowlivingco",
    displayName: "Slow Living Co",
    bio: "Mindful routines, seasonal rituals, and low-key lifestyle challenges.",
    category: "Lifestyle",
    tokenName: "Slow",
    tokenSymbol: "SLOW",
    followersCount: 7_200,
    activeChallengesCount: 0,
    perksCount: 1,
    verified: false,
    featured: false,
    trending: false,
    recentlyActive: false,
    createdAt: "2025-06-19T00:00:00.000Z",
    source: "demo",
  },
  {
    id: "lex-learns",
    handle: "lexlearns",
    displayName: "Lex Learns",
    bio: "Teaching creative skills through bite-sized lessons and cohorts.",
    category: "Education",
    tokenName: "Lex",
    tokenSymbol: "LEX",
    followersCount: 5_400,
    activeChallengesCount: 0,
    perksCount: 1,
    verified: true,
    featured: false,
    trending: true,
    recentlyActive: true,
    createdAt: "2025-07-05T00:00:00.000Z",
    source: "demo",
  },
];

export const DEMO_CHALLENGES: readonly CatalogChallenge[] = [
  {
    id: "cover-art-single",
    creatorId: "lena-music",
    creatorHandle: "lenamusic",
    creatorName: "Lena Music",
    title: "Design the cover for my next single",
    description:
      "Design a bold, single-ready cover for Lena's next release. Any style is welcome—make it unmistakably hers.",
    status: "published",
    submissionKind: "image",
    verificationMode: "manual",
    requiresWorldVerification: true,
    rewardAmount: "700",
    maxWinners: 1,
    winnerCount: 0,
    submissionCount: 312,
    startsAt: "2026-07-01T12:00:00.000Z",
    submissionDeadline: "2026-08-02T12:00:00.000Z",
    createdAt: "2026-07-01T12:00:00.000Z",
    featured: true,
    source: "demo",
  },
  {
    id: "best-edit-video",
    creatorId: "nova-wave",
    creatorHandle: "novawave",
    creatorName: "Nova Wave",
    title: "Create the best edit from my latest video",
    description:
      "Cut together your favorite moments from Nova's latest drop. The best edit gets featured on her channel.",
    status: "published",
    submissionKind: "video",
    verificationMode: "manual",
    requiresWorldVerification: true,
    rewardAmount: "1000",
    maxWinners: 1,
    winnerCount: 0,
    submissionCount: 189,
    startsAt: "2026-07-05T12:00:00.000Z",
    submissionDeadline: "2026-08-05T12:00:00.000Z",
    createdAt: "2026-07-05T12:00:00.000Z",
    featured: true,
    source: "demo",
  },
  {
    id: "mascot-outfit",
    creatorId: "mika-live",
    creatorHandle: "mikalive",
    creatorName: "Mika Live",
    title: "Draw a new outfit for the mascot",
    description:
      "Reimagine Mika's mascot in a fresh outfit. Sketch, paint, or render—surprise the community.",
    status: "published",
    submissionKind: "image",
    verificationMode: "manual",
    requiresWorldVerification: true,
    rewardAmount: "500",
    maxWinners: 3,
    winnerCount: 0,
    submissionCount: 421,
    startsAt: "2026-07-08T12:00:00.000Z",
    submissionDeadline: "2026-08-09T12:00:00.000Z",
    createdAt: "2026-07-08T12:00:00.000Z",
    featured: true,
    source: "demo",
  },
  {
    id: "live-show-concept",
    creatorId: "beatlab",
    creatorHandle: "beatlab",
    creatorName: "BeatLab",
    title: "Suggest the concept for my next live show",
    description:
      "Pitch the theme, setlist, or format for BeatLab's next live show. The strongest concept gets produced.",
    status: "published",
    submissionKind: "text",
    verificationMode: "manual",
    requiresWorldVerification: false,
    rewardAmount: "800",
    maxWinners: 1,
    winnerCount: 0,
    submissionCount: 97,
    startsAt: "2026-07-10T12:00:00.000Z",
    submissionDeadline: "2026-08-06T12:00:00.000Z",
    createdAt: "2026-07-10T12:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "fan-trailer",
    creatorId: "ava-studio",
    creatorHandle: "avastudio",
    creatorName: "Ava Studio",
    title: "Create a fan trailer",
    description:
      "Cut a trailer that captures the Ava Studio vibe. Keep it short, punchy, and shareable.",
    status: "published",
    submissionKind: "video",
    verificationMode: "manual",
    requiresWorldVerification: true,
    rewardAmount: "1200",
    maxWinners: 1,
    winnerCount: 0,
    submissionCount: 64,
    startsAt: "2026-07-12T12:00:00.000Z",
    submissionDeadline: "2026-08-12T12:00:00.000Z",
    createdAt: "2026-07-12T12:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "merch-design-vote",
    creatorId: "lena-music",
    creatorHandle: "lenamusic",
    creatorName: "Lena Music",
    title: "Choose the next merch design",
    description:
      "Submit your take on Lena's next merch drop before it goes into production.",
    status: "published",
    submissionKind: "image",
    verificationMode: "manual",
    requiresWorldVerification: false,
    rewardAmount: "350",
    maxWinners: 2,
    winnerCount: 0,
    submissionCount: 0,
    startsAt: "2026-07-30T12:00:00.000Z",
    submissionDeadline: "2026-08-18T12:00:00.000Z",
    createdAt: "2026-07-15T12:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "cosplay-recreation",
    creatorId: "mika-live",
    creatorHandle: "mikalive",
    creatorName: "Mika Live",
    title: "Recreate the ultimate cosplay look",
    description:
      "Recreate your favorite look with your own spin. Accuracy and creativity both count.",
    status: "completed",
    submissionKind: "image",
    verificationMode: "manual",
    requiresWorldVerification: true,
    rewardAmount: "650",
    maxWinners: 1,
    winnerCount: 1,
    submissionCount: 288,
    startsAt: "2026-05-01T12:00:00.000Z",
    submissionDeadline: "2026-06-01T12:00:00.000Z",
    createdAt: "2026-05-01T12:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "remix-track",
    creatorId: "beatlab",
    creatorHandle: "beatlab",
    creatorName: "BeatLab",
    title: "Remix my new track",
    description:
      "Remix BeatLab's newest track into something entirely your own. Any genre is welcome.",
    status: "judging",
    submissionKind: "link",
    verificationMode: "manual",
    requiresWorldVerification: true,
    rewardAmount: "900",
    maxWinners: 2,
    winnerCount: 0,
    submissionCount: 156,
    startsAt: "2026-06-20T12:00:00.000Z",
    submissionDeadline: "2026-07-25T12:00:00.000Z",
    createdAt: "2026-06-20T12:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "fanfic-chapter",
    creatorId: "ava-studio",
    creatorHandle: "avastudio",
    creatorName: "Ava Studio",
    title: "Write the next chapter with me",
    description:
      "Add the next chapter to an ongoing community story—keep the tone, then take it anywhere.",
    status: "published",
    submissionKind: "text",
    verificationMode: "manual",
    requiresWorldVerification: false,
    rewardAmount: "250",
    maxWinners: 5,
    winnerCount: 0,
    submissionCount: 43,
    startsAt: "2026-07-18T12:00:00.000Z",
    submissionDeadline: "2026-08-08T12:00:00.000Z",
    createdAt: "2026-07-18T12:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "dream-portfolio-link",
    creatorId: "nova-wave",
    creatorHandle: "novawave",
    creatorName: "Nova Wave",
    title: "Share your dream portfolio link",
    description:
      "Drop a link to your portfolio, playlist, or project page. The best one gets shared with Nova's audience.",
    status: "published",
    submissionKind: "link",
    verificationMode: "automatic",
    requiresWorldVerification: true,
    rewardAmount: "300",
    maxWinners: 3,
    winnerCount: 0,
    submissionCount: 72,
    startsAt: "2026-07-20T12:00:00.000Z",
    submissionDeadline: "2026-08-14T12:00:00.000Z",
    createdAt: "2026-07-20T12:00:00.000Z",
    featured: false,
    source: "demo",
  },
];

export const DEMO_PERKS: readonly CatalogPerk[] = [
  {
    id: "lena-signed-vinyl",
    creatorId: "lena-music",
    creatorHandle: "lenamusic",
    creatorName: "Lena Music",
    title: "Signed limited-edition vinyl",
    description: "A numbered pressing signed by Lena and shipped worldwide.",
    category: "Merch",
    tokenThreshold: "2500",
    tokenSymbol: "LENA",
    inventory: 75,
    claimedCount: 41,
    status: "active",
    requiresWorldVerification: true,
    createdAt: "2026-06-12T00:00:00.000Z",
    featured: true,
    source: "demo",
  },
  {
    id: "lena-listening-party",
    creatorId: "lena-music",
    creatorHandle: "lenamusic",
    creatorName: "Lena Music",
    title: "Private album listening party",
    description: "Join a live pre-release listening room and Q&A with Lena.",
    category: "Experience",
    tokenThreshold: "5000",
    tokenSymbol: "LENA",
    inventory: 40,
    claimedCount: 18,
    status: "active",
    requiresWorldVerification: true,
    createdAt: "2026-07-02T00:00:00.000Z",
    featured: true,
    source: "demo",
  },
  {
    id: "lena-stems-pack",
    creatorId: "lena-music",
    creatorHandle: "lenamusic",
    creatorName: "Lena Music",
    title: "Studio stems download",
    description:
      "Download stems from Lena's latest single for personal remixes.",
    category: "Digital",
    tokenThreshold: "750",
    tokenSymbol: "LENA",
    inventory: 500,
    claimedCount: 126,
    status: "active",
    requiresWorldVerification: false,
    createdAt: "2026-05-22T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "nova-editing-masterclass",
    creatorId: "nova-wave",
    creatorHandle: "novawave",
    creatorName: "Nova Wave",
    title: "Editing workflow masterclass",
    description: "A live breakdown of Nova's edit, color, and sound workflow.",
    category: "Experience",
    tokenThreshold: "1800",
    tokenSymbol: "NOVA",
    inventory: 100,
    claimedCount: 63,
    status: "active",
    requiresWorldVerification: true,
    createdAt: "2026-06-28T00:00:00.000Z",
    featured: true,
    source: "demo",
  },
  {
    id: "nova-lut-pack",
    creatorId: "nova-wave",
    creatorHandle: "novawave",
    creatorName: "Nova Wave",
    title: "Signature LUT pack",
    description: "Nova's production-ready color presets for desktop editors.",
    category: "Digital",
    tokenThreshold: "400",
    tokenSymbol: "NOVA",
    inventory: 1000,
    claimedCount: 404,
    status: "active",
    requiresWorldVerification: false,
    createdAt: "2026-04-08T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "mika-stream-cameo",
    creatorId: "mika-live",
    creatorHandle: "mikalive",
    creatorName: "Mika Live",
    title: "Guest cameo on stream",
    description: "Join Mika live for a ten-minute community spotlight segment.",
    category: "Experience",
    tokenThreshold: "7500",
    tokenSymbol: "MIKA",
    inventory: 12,
    claimedCount: 9,
    status: "active",
    requiresWorldVerification: true,
    createdAt: "2026-07-06T00:00:00.000Z",
    featured: true,
    source: "demo",
  },
  {
    id: "mika-emote-pack",
    creatorId: "mika-live",
    creatorHandle: "mikalive",
    creatorName: "Mika Live",
    title: "Founders emote pack",
    description: "A downloadable pack of community-designed Mika emotes.",
    category: "Digital",
    tokenThreshold: "600",
    tokenSymbol: "MIKA",
    inventory: 800,
    claimedCount: 267,
    status: "active",
    requiresWorldVerification: false,
    createdAt: "2026-05-30T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "beatlab-feedback-session",
    creatorId: "beatlab",
    creatorHandle: "beatlab",
    creatorName: "BeatLab",
    title: "One-on-one track feedback",
    description: "A private 30-minute production feedback call with BeatLab.",
    category: "Experience",
    tokenThreshold: "4000",
    tokenSymbol: "BEAT",
    inventory: 20,
    claimedCount: 20,
    status: "exhausted",
    requiresWorldVerification: true,
    createdAt: "2026-03-18T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "beatlab-sample-pack",
    creatorId: "beatlab",
    creatorHandle: "beatlab",
    creatorName: "BeatLab",
    title: "Community sample pack",
    description:
      "Royalty-free drums, loops, and one-shots from BeatLab sessions.",
    category: "Digital",
    tokenThreshold: "500",
    tokenSymbol: "BEAT",
    inventory: 1200,
    claimedCount: 513,
    status: "active",
    requiresWorldVerification: false,
    createdAt: "2026-06-04T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "ava-art-print",
    creatorId: "ava-studio",
    creatorHandle: "avastudio",
    creatorName: "Ava Studio",
    title: "Museum-grade art print",
    description: "Choose one of three community favorites, signed by Ava.",
    category: "Merch",
    tokenThreshold: "2200",
    tokenSymbol: "AVA",
    inventory: 60,
    claimedCount: 22,
    status: "active",
    requiresWorldVerification: true,
    createdAt: "2026-06-15T00:00:00.000Z",
    featured: true,
    source: "demo",
  },
  {
    id: "ava-wallpaper-collection",
    creatorId: "ava-studio",
    creatorHandle: "avastudio",
    creatorName: "Ava Studio",
    title: "Animated wallpaper collection",
    description: "A set of 4K looping scenes from Ava's latest world.",
    category: "Digital",
    tokenThreshold: "350",
    tokenSymbol: "AVA",
    inventory: 1500,
    claimedCount: 682,
    status: "active",
    requiresWorldVerification: false,
    createdAt: "2026-05-05T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "rue-lookbook",
    creatorId: "rue-archive",
    creatorHandle: "ruearchive",
    creatorName: "Rue Archive",
    title: "Seasonal digital lookbook",
    description: "The complete collection notes, styling guide, and sketches.",
    category: "Digital",
    tokenThreshold: "450",
    tokenSymbol: "RUE",
    inventory: 600,
    claimedCount: 192,
    status: "active",
    requiresWorldVerification: false,
    createdAt: "2026-04-21T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "pixel-beta-access",
    creatorId: "pixel-forge",
    creatorHandle: "pixelforge",
    creatorName: "Pixel Forge",
    title: "Early game beta access",
    description:
      "Play the next Pixel Forge build and join the private feedback server.",
    category: "Digital",
    tokenThreshold: "900",
    tokenSymbol: "PXL",
    inventory: 300,
    claimedCount: 211,
    status: "active",
    requiresWorldVerification: true,
    createdAt: "2026-06-24T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "slow-seasonal-workshop",
    creatorId: "slow-living-co",
    creatorHandle: "slowlivingco",
    creatorName: "Slow Living Co",
    title: "Seasonal planning workshop",
    description: "A small-group workshop for designing a calmer month.",
    category: "Experience",
    tokenThreshold: "1200",
    tokenSymbol: "SLOW",
    inventory: 50,
    claimedCount: 31,
    status: "paused",
    requiresWorldVerification: true,
    createdAt: "2026-05-14T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
  {
    id: "lex-course-notes",
    creatorId: "lex-learns",
    creatorHandle: "lexlearns",
    creatorName: "Lex Learns",
    title: "Complete course notes bundle",
    description:
      "Exercises, templates, and annotated notes from Lex's creative series.",
    category: "Digital",
    tokenThreshold: "300",
    tokenSymbol: "LEX",
    inventory: 2000,
    claimedCount: 744,
    status: "active",
    requiresWorldVerification: false,
    createdAt: "2026-07-09T00:00:00.000Z",
    featured: false,
    source: "demo",
  },
];
